from . import product_template
from . import res_partner
from . import x_choferes
from . import sale_order
from . import stock_picking
from . import stock_picking_type
from . import stock_move
from . import stock_lot
from . import stock_quant
from . import trigas_delivery_signature_record
